[package]
name = "webrtc-sfu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "webrtc-sfu"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.45"
async-trait = "0.1.51"
base64 = "0.13.0"
log = "0.4.14"
nats = "0.15.2"
once_cell = "1.8.0"
serde = "1.0.130"
serde_json = "1.0.69"
tokio = { version = "1.13.0", features = ["full"] }
clap = "3.0.0-beta.5"
redis = { version = "0.21.4", features = ["tokio-comp"] }
# WebRTC
webrtc = { git = "https://github.com/webrtc-rs/webrtc", rev = "6fc9ddb" }
# tracing ecosystem
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.1", features = ["fmt", "env-filter"] }
console-subscriber = { git = "https://github.com/tokio-rs/console", rev = "a30264e" }
# web server
actix-web = { version = "4.0.0-beta.11", features = ["rustls"] } # web framework
actix-web-httpauth = { version = "0.6.0-beta.3" }   # bearerer token
actix-files = "0.6.0-beta.8"    # static files
actix-cors = "0.6.0-beta.3"     # CORS setting (for easier frontend local development)
rustls = "0.20.0"               # SSL
rustls-pemfile = "0.2.1"        # SSL
