[package]
name = "rtc-nats"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.0-beta.2"
actix-files = "0.6.0-beta.7"
actix-web = "4.0.0-beta.9"
actix-web-httpauth = "0.6.0-beta.2"
anyhow = "1.0.44"
base64 = "0.13.0"
env_logger = "0.9.0"
interceptor = "0.1.3"
log = "0.4.14"
nats = "0.15.2"
rtcp = "0.3.4"
rtp = "0.3.5"
serde = "1.0.130"
serde_json = "1.0.68"
tokio = { version = "1.12.0", features=["full"] }
webrtc = "0.1.1"
webrtc-util = "0.4.3"
